# hadolint global ignore=DL3016

ARG VERSION
FROM davidanson/markdownlint-cli2:${VERSION}

USER root

RUN npm install --global --no-package-lock --production \
    @github/markdownlint-github \
    markdownlint-rule-enhanced-proper-names \
    markdownlint-rule-extended-ascii \
    markdownlint-rule-github-admonition \
    markdownlint-rule-github-internal-links \
    markdownlint-rule-header-id \
    markdownlint-rule-list-duplicates \
    markdownlint-rule-max-one-sentence-per-line \
    markdownlint-rule-no-trailing-slash-in-links \
    markdownlint-rule-olstart \
    markdownlint-rule-relative-links \
    markdownlint-rule-search-replace \
    markdownlint-rule-title-case-style \
    markdownlint-rule-titlecase \
    markdownlint-rule-trace-template-headers \
    markdownlint-rules-foliant \
    markdownlint-rules-grav-pages \
    sentences-per-line

USER node
