# hadolint global ignore=DL3016

ARG VERSION
FROM davidanson/markdownlint-cli2:${VERSION}

USER 0
# 0 is the documented user ID for the "root" user: https://www.docker.com/blog/understanding-the-docker-user-instruction

RUN npm install --global --no-package-lock --omit=dev \
    @github/markdownlint-github \
    markdownlint-rule-enhanced-proper-names \
    markdownlint-rule-extended-ascii \
    markdownlint-rule-github-admonition \
    markdownlint-rule-github-internal-links \
    markdownlint-rule-header-id \
    markdownlint-rule-list-duplicates \
    markdownlint-rule-max-one-sentence-per-line \
    markdownlint-rule-no-trailing-slash-in-links \
    markdownlint-rule-numbered-headings-unique \
    markdownlint-rule-olstart \
    markdownlint-rule-relative-links \
    markdownlint-rule-search-replace \
    markdownlint-rule-title-case-style \
    markdownlint-rule-titlecase \
    markdownlint-rule-trace-template-headers \
    markdownlint-rules-foliant \
    markdownlint-rules-grav-pages \
    mkdocs-material-linter \
    sentences-per-line

USER 1000
# 1000 is the documented user ID for the unprivileged "node" user: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user
# Kubernetes running as non-root requires user ID (implied by the docs for "runAsUser"): https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#securitycontext-v1-core
